// Send weekly report to DingTalk — short message with PDF/download link.
// If PDF is not available, falls back to sending full markdown in chunks.
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const mdPath = resolve(process.argv[2] || 'out/latest-report.md');
const webhookUrl = process.env.DINGTALK_WEBHOOK_URL;
const secret = process.env.DINGTALK_SECRET || '';
const noDelivery = process.env.NO_DELIVERY === '1';
const DINGTALK_BYTE_LIMIT = 18000;
const encoder = new TextEncoder();

if (noDelivery) {
  console.log('NO_DELIVERY=1, skipping DingTalk push');
  process.exit(0);
}
if (!webhookUrl) {
  console.error('DINGTALK_WEBHOOK_URL not set');
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);

// Check for PDF URL (generated by render-report-pdf.js)
const urlPath = resolve('out/report-url.txt');
const pdfUrl = existsSync(urlPath) ? readFileSync(urlPath, 'utf8').trim() : '';

if (pdfUrl) {
  // Short message with PDF download link
  const artifactUrl = `https://github.com/zhuxinfei/beauty-legal-bot/actions/runs/${process.env.GITHUB_RUN_ID}`;
  const msg = [
    `# 美妆法务资讯周报｜${today}`,
    '',
    `📄 [查看完整报告](${pdfUrl})`,
    '',
    `> 🔗 [GitHub Actions 运行记录](${artifactUrl})`,
    '',
    `---`,
    `*杭州丽知法务部 · 自动生成 · ${today}*`,
  ].join('\n');

  const body = JSON.stringify({ msgtype: 'markdown', markdown: { title: `美妆法务资讯周报｜${today}`, text: msg } });
  const url = secret ? await buildSignedUrl(webhookUrl, secret, Date.now()) : webhookUrl;
  const resp = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body });
  const result = await resp.json();
  console.log(`DingTalk: ${result.errcode === 0 ? 'OK' : 'FAILED: ' + result.errmsg}`);
  process.exit(result.errcode === 0 ? 0 : 1);
}

// Fallback: send full markdown in chunks
const fullMarkdown = readFileSync(mdPath, 'utf8');
console.log(`No PDF URL, sending full markdown (${encoder.encode(fullMarkdown).length} bytes)`);

// Split at card boundaries
const lines = fullMarkdown.split('\n');
const headerEnd = lines.findIndex((l, i) => i > 0 && l.startsWith('## '));
const header = lines.slice(0, headerEnd > 0 ? headerEnd : 2).join('\n') + '\n';
const cards = [];
let cur = [];
for (const line of lines) {
  if (line.startsWith('### ')) { if (cur.length) cards.push(cur.join('\n')); cur = [line]; }
  else if (cur.length || line.startsWith('## ')) cur.push(line);
}
if (cur.length) cards.push(cur.join('\n'));

const chunks = [];
let chunk = '';
for (const card of cards) {
  const candidate = chunk ? chunk + '\n' + card : header + '\n' + card;
  if (encoder.encode(candidate).length > DINGTALK_BYTE_LIMIT && chunk) { chunks.push(chunk); chunk = header + '\n' + card; }
  else chunk = candidate;
}
if (chunk) chunks.push(chunk);

let cardNumber = 0;
for (let i = 0; i < chunks.length; i++) {
  let c = chunks[i];
  c = c.replace(/^### \d+\./gm, () => { cardNumber++; return `### ${cardNumber}.`; });
  const bytes = encoder.encode(c).length;
  const label = chunks.length > 1 ? `美妆法务资讯｜${today}（${i + 1}/${chunks.length}）` : `美妆法务资讯｜${today}`;
  const body = JSON.stringify({ msgtype: 'markdown', markdown: { title: label, text: c } });
  const url = secret ? await buildSignedUrl(webhookUrl, secret, Date.now()) : webhookUrl;
  const resp = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body });
  const result = await resp.json();
  if (result.errcode !== 0) { console.error(`Chunk ${i + 1} failed: ${result.errmsg}`); process.exit(1); }
  console.log(`Chunk ${i + 1}/${chunks.length}: OK (${bytes}B)`);
}
console.log('Delivery complete');

async function buildSignedUrl(webhook, sec, ts) {
  const { createHmac } = await import('node:crypto');
  const sign = createHmac('sha256', sec).update(`${ts}\n${sec}`).digest('base64');
  return `${webhook}&timestamp=${ts}&sign=${encodeURIComponent(sign)}`;
}
